
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Karma Health Demo
* Environment: Production
* Id: d89e24b9-c2c4-0153-3e3b-8d8abd406750
* 
* -------------------------------------------------------------------------------
**/

/**
 * Type representing all languages
 */
export type LanguageCodenames = "de-DE" | "default" | "es-ES";

/**
 * Type representing all content types
 */
export type ContentTypeCodenames =
  | "article"
  | "blog"
  | "disclaimer"
  | "event"
  | "landing_page"
  | "page"
  | "person"
  | "service"
  | "video";

/**
 * Type representing all collections
 */
export type CollectionCodenames = "default";

/**
 * Type representing all workflows
 */
export type WorkflowCodenames = "default";

/**
 * Type representing all taxonomies
 */
export type TaxonomyCodenames =
  | "article_type"
  | "event_topic"
  | "event_type"
  | "general_healthcare_topics"
  | "medical_specialties";

/**
 * Type representing all worksflow steps across all workflows
 */
export type WorkflowStepCodenames = "archived" | "draft" | "published" | "scheduled";

/**
 * Type representing all element codenames across all content types
 */
export type ElementCodenames =
  | "article_type"
  | "author"
  | "autoplay"
  | "biography"
  | "body_copy"
  | "body"
  | "caption"
  | "content"
  | "description"
  | "email"
  | "end_date"
  | "event_topic"
  | "event_type"
  | "featured_content"
  | "first_name"
  | "guidelines"
  | "headline"
  | "hero_image"
  | "image"
  | "introduction"
  | "job_title"
  | "last_name"
  | "medical_specialties"
  | "metadata__description"
  | "metadata__keywords"
  | "metadata__title"
  | "metadata"
  | "name"
  | "phone"
  | "prefix"
  | "publish_date"
  | "start_date"
  | "subheadline"
  | "subpages"
  | "team"
  | "title"
  | "topics"
  | "type"
  | "url"
  | "video_link"
  | "website";
