
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-19'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Production
* Id: 133f5ef8-66b1-0074-7d42-55371447aac4
* 
* -------------------------------------------------------------------------------
**/

export const contentTypes = {
  /**
   * Event
   */
  event: {
    name: "Event",
    codename: "event",
    id: "e97907ba-c5ae-53e6-bcb6-091bc89da3fa",
    externalId: "event",
    elements: {
      /**
       * Name (text)
       */
      name: {
        name: "Name",
        codename: "name",
        id: "60502ad7-d552-5435-af46-6f4df84c3ddd",
        externalId: "event_default_name_element",
        required: false,
        type: "text",
      },

      /**
       * Description (rich_text)
       */
      description: {
        name: "Description",
        codename: "description",
        id: "2a7a8e84-274c-5339-afd2-4865b643fbb2",
        externalId: "event_default_description_element",
        required: false,
        type: "rich_text",
      },

      /**
       * Image (asset)
       */
      image: {
        name: "Image",
        codename: "image",
        id: "b13e797e-0e50-5ecb-aebc-05aa9e180864",
        externalId: "event_default_image_element",
        required: false,
        type: "asset",
      },

      /**
       * Start Date (date_time)
       */
      start_date: {
        name: "Start Date",
        codename: "start_date",
        id: "114ba02d-f9dd-5555-a78d-6798d1a835a0",
        externalId: "event_default_start_date_element",
        required: false,
        type: "date_time",
      },

      /**
       * End Date (date_time)
       */
      end_date: {
        name: "End Date",
        codename: "end_date",
        id: "a00fecf1-c7ff-5bed-8c40-2eba7460170a",
        externalId: "event_default_end_date_element",
        required: false,
        type: "date_time",
      },

      /**
       * Event Type (taxonomy)
       */
      event_type: {
        name: "Event Type",
        codename: "event_type",
        id: "aa177aeb-9cd0-5a3a-a6b6-ca055fe2cae3",
        externalId: "event_default_event_type_element",
        required: false,
        type: "taxonomy",
      },

      /**
       * Event Topic (taxonomy)
       */
      event_topic: {
        name: "Event Topic",
        codename: "event_topic",
        id: "0da8a57d-a1d5-5b1e-9b6e-6d28dc1a6caa",
        externalId: "event_default_event_topic_element",
        required: false,
        type: "taxonomy",
      },
    },
  },

  /**
   * Solution
   */
  solution: {
    name: "Solution",
    codename: "solution",
    id: "f3df0cce-53f0-4ab1-875c-dd5c5d57a0ba",
    externalId: undefined,
    elements: {
      /**
       * Headline (text)
       */
      headline: {
        name: "Headline",
        codename: "headline",
        id: "677e82da-9f88-49ca-9c73-2689709cbbdf",
        externalId: undefined,
        required: true,
        type: "text",
      },

      /**
       * Introduction (text)
       */
      introduction: {
        name: "Introduction",
        codename: "introduction",
        id: "c588ca2a-5cac-47b3-897d-96995c17e1f8",
        externalId: undefined,
        required: true,
        type: "text",
      },

      /**
       * Image (asset)
       */
      image: {
        name: "Image",
        codename: "image",
        id: "819f6844-4230-4ae1-ade7-ddb6e62ca7bd",
        externalId: undefined,
        required: true,
        type: "asset",
      },
    },
  },

  /**
   * Video
   */
  video: {
    name: "Video",
    codename: "video",
    id: "5b2003c5-fe38-5a6e-a21b-a7b2f5ee0ddb",
    externalId: "video",
    elements: {
      /**
       * Headline (text)
       */
      headline: {
        name: "Headline",
        codename: "headline",
        id: "0bd216b2-4975-50f9-832e-6e2c6c5d1bf9",
        externalId: "video_default_headline_element",
        required: false,
        type: "text",
      },

      /**
       * Description (text)
       */
      description: {
        name: "Description",
        codename: "description",
        id: "c454e463-2c85-57a2-aec8-e399a392b229",
        externalId: "video_default_description_element",
        required: false,
        type: "text",
      },

      /**
       * Video Link (text)
       */
      video_link: {
        name: "Video Link",
        codename: "video_link",
        id: "09573446-747b-572e-af77-9cbf359bcdad",
        externalId: "video_default_video_link_element",
        required: false,
        type: "text",
      },

      /**
       * Caption (text)
       */
      caption: {
        name: "Caption",
        codename: "caption",
        id: "c3054bab-604f-5d9d-bf1f-06c87cd5b15e",
        externalId: "video_default_caption_element",
        required: false,
        type: "text",
      },

      /**
       * Autoplay (multiple_choice)
       */
      autoplay: {
        name: "Autoplay",
        codename: "autoplay",
        id: "21250a1b-2eff-52cc-89b2-a44a2bab8b93",
        externalId: "video_default_autoplay_element",
        required: false,
        type: "multiple_choice",
        options: {
          /**
           * True
           */
          true: {
            name: "True",
            id: "3c1cbb5a-8eb8-591a-8e99-15d85ea5c276",
            codename: "true",
            externalId: "video_autoplay_true",
          },

          /**
           * False
           */
          false: {
            name: "False",
            id: "118a4d40-b4a6-5d04-89cc-6a182245b8f9",
            codename: "false",
            externalId: "video_autoplay_false",
          },
        },
      },
    },
  },

  /**
   * Landing Page
   */
  landing_page: {
    name: "Landing Page",
    codename: "landing_page",
    id: "aa610b72-ca00-5ee3-bd30-f5b001b9d64e",
    externalId: "landing_page",
    elements: {
      /**
       * Headline (text)
       */
      headline: {
        name: "Headline",
        codename: "headline",
        id: "ff2c9d21-64f1-5d64-b650-344dd0ba44d2",
        externalId: "landing_page_default_headline_element",
        required: false,
        type: "text",
      },

      /**
       * Subheadline (text)
       */
      subheadline: {
        name: "Subheadline",
        codename: "subheadline",
        id: "96fa63e6-2f46-557d-9dc8-4874ae9340a6",
        externalId: "landing_page_default_subheadline_element",
        required: false,
        type: "text",
      },

      /**
       * Hero Image (asset)
       */
      hero_image: {
        name: "Hero Image",
        codename: "hero_image",
        id: "efe09118-3de6-5581-b784-43408e2e673b",
        externalId: "landing_page_default_hero_image_element",
        required: false,
        type: "asset",
      },

      /**
       * Body Copy (rich_text)
       */
      body_copy: {
        name: "Body Copy",
        codename: "body_copy",
        id: "b0e94942-8d23-5f67-aa72-15c0ed45a390",
        externalId: "landing_page_default_body_copy_element",
        required: false,
        type: "rich_text",
      },

      /**
       * Featured Content (modular_content)
       */
      featured_content: {
        name: "Featured Content",
        codename: "featured_content",
        id: "7f939caa-a3a2-5018-a127-fe2938129fa9",
        externalId: "landing_page_default_featured_content_element",
        required: false,
        type: "modular_content",
      },
    },
  },

  /**
   * Article
   */
  article: {
    name: "Article",
    codename: "article",
    id: "d622fc28-5202-511a-9dbf-a3ee363b6c7c",
    externalId: "article",
    elements: {
      /**
       * Title (text)
       */
      title: {
        name: "Title",
        codename: "title",
        id: "ad06c69a-9ccd-5d8c-b2de-b6a9f83d00fc",
        externalId: "article_default_title_element",
        required: false,
        type: "text",
      },

      /**
       * Introduction (text)
       */
      introduction: {
        name: "Introduction",
        codename: "introduction",
        id: "c3fc1a88-5577-5130-b0aa-b1837c009ba6",
        externalId: "article_default_introduction_element",
        required: false,
        type: "text",
      },

      /**
       * Image (asset)
       */
      image: {
        name: "Image",
        codename: "image",
        id: "8c501358-d0f7-5959-95bd-2991f1215e33",
        externalId: "article_default_image_element",
        required: false,
        type: "asset",
      },

      /**
       * Body Copy (rich_text)
       */
      body_copy: {
        name: "Body Copy",
        codename: "body_copy",
        id: "0747fb13-7383-59fe-bf64-2bab6d384279",
        externalId: "article_default_body_copy_element",
        required: false,
        type: "rich_text",
      },

      /**
       * Publish Date (date_time)
       */
      publish_date: {
        name: "Publish Date",
        codename: "publish_date",
        id: "abdf08ea-55f0-5460-96e0-391f7471c7e9",
        externalId: "article_default_publish_date_element",
        required: false,
        type: "date_time",
      },
    },
  },
} as const;
