
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-19'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Production
* Id: 133f5ef8-66b1-0074-7d42-55371447aac4
* 
* -------------------------------------------------------------------------------
**/

export const languages = {
  /**
   * Default project language
   */
  default: {
    name: "Default project language",
    codename: "default",
    id: "00000000-0000-0000-0000-000000000000",
    isActive: true,
    isDefault: true,
    fallbackLanguageId: "00000000-0000-0000-0000-000000000000",
    externalId: undefined,
  },
} as const;
