
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-19'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Production
* Id: 133f5ef8-66b1-0074-7d42-55371447aac4
* 
* -------------------------------------------------------------------------------
**/

export const spaces = {
  /**
   * Default Space
   */
  defaultSpace: {
    name: "Default Space",
    codename: "default_space",
    id: "e6fa1437-2367-4c8b-bb11-45ecccef6311",
  },
} as const;
