
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-19'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Production
* Id: 133f5ef8-66b1-0074-7d42-55371447aac4
* 
* -------------------------------------------------------------------------------
**/

export const taxonomies = {
  /**
   * event_type
   */
  event_type: {
    name: "Event Type",
    codename: "event_type",
    externalId: "event_type",
    id: "54519543-3e87-541d-a060-1246d721db5e",
    terms: {
      /**
       * Seminar
       */
      seminar: {
        name: "Seminar",
        codename: "seminar",
        id: "922336e0-b82a-5589-ae5d-8a3bb426ad9a",
        externalId: "event_type_seminar",
        terms: {},
      },

      /**
       * Webinar
       */
      webinar: {
        name: "Webinar",
        codename: "webinar",
        id: "3b9e5257-cdbb-50ad-85be-0e8986745cdf",
        externalId: "event_type_webinar",
        terms: {},
      },

      /**
       * Workshop
       */
      workshop: {
        name: "Workshop",
        codename: "workshop",
        id: "707bb142-f7d5-574a-b0ba-63037c412d84",
        externalId: "event_type_workshop",
        terms: {},
      },
    },
  },

  /**
   * event_topic
   */
  event_topic: {
    name: "Event Topic",
    codename: "event_topic",
    externalId: "event_topic",
    id: "c73d35c2-df63-53f5-a9e5-a8450b027704",
    terms: {
      /**
       * Nutrition
       */
      nutrition: {
        name: "Nutrition",
        codename: "nutrition",
        id: "33b8eafc-080f-51ac-8fd8-ddf043551dd3",
        externalId: "event_topic_nutrition",
        terms: {},
      },

      /**
       * Physical Fitness
       */
      physical_fitness: {
        name: "Physical Fitness",
        codename: "physical_fitness",
        id: "b1e860df-6000-5db1-8e17-12362bc65bc0",
        externalId: "event_topic_physical_fitness",
        terms: {},
      },

      /**
       * Preventative Care
       */
      preventative_care: {
        name: "Preventative Care",
        codename: "preventative_care",
        id: "17ac481e-30ef-5021-92c5-c2e335b922ab",
        externalId: "event_topic_preventative_care",
        terms: {},
      },
    },
  },
} as const;
