
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Karma Health Demo
* Environment: Production
* Id: d89e24b9-c2c4-0153-3e3b-8d8abd406750
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Medical Specialties
 *
 * Codename: medical_specialties
 * Id: 22981808-66a0-4d9a-8aa7-4d92f04ead5a
 */
export const medicalSpecialtiesValues = [
  "cardiology",
  "oncology",
  "neurology",
  "pediatrics",
  "orthopedics",
  "endocrinology",
  "dermatology",
] as const;

/**
 * Type representing Medical Specialties taxonomy
 *
 * Codename: medical_specialties
 * Id: 22981808-66a0-4d9a-8aa7-4d92f04ead5a
 */
export type MedicalSpecialties = (typeof medicalSpecialtiesValues)[number];

/**
 * Type guard for Medical Specialties
 *
 * Codename: medical_specialties
 * Id: 22981808-66a0-4d9a-8aa7-4d92f04ead5a
 */
export function isMedicalSpecialties(value: string | undefined | null): value is MedicalSpecialties {
  return typeof value === "string" && (medicalSpecialtiesValues as readonly string[]).includes(value);
}
