
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Karma Health Demo
* Environment: Production
* Id: d89e24b9-c2c4-0153-3e3b-8d8abd406750
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { ArticleType, GeneralHealthcareTopics } from "../taxonomies/index.ts";
import type { CoreContentType } from "../system/index.ts";
import type { Person } from "./index.ts";

/**
 * Article
 *
 * Id: d622fc28-5202-511a-9dbf-a3ee363b6c7c
 * Codename: article
 */
export type Article = CoreContentType<
  ArticleElementCodenames,
  {
    /**
     * Title
     *
     * Type: text
     * Required: true
     * Codename: title
     * Id: ad06c69a-9ccd-5d8c-b2de-b6a9f83d00fc
     */
    readonly title: Elements.TextElement;
    /**
     * Publish Date
     *
     * Type: date_time
     * Required: true
     * Codename: publish_date
     * Id: abdf08ea-55f0-5460-96e0-391f7471c7e9
     */
    readonly publish_date: Elements.DateTimeElement;
    /**
     * Introduction
     *
     * Type: text
     * Required: true
     * Codename: introduction
     * Id: c3fc1a88-5577-5130-b0aa-b1837c009ba6
     */
    readonly introduction: Elements.TextElement;
    /**
     * Author
     *
     * Type: modular_content
     * Required: false
     * Codename: author
     * Id: 645445ef-c1a0-4eec-bbec-fcb2ce2e1862
     */
    readonly author: Elements.LinkedItemsElement<Person>;
    /**
     * Image
     *
     * Type: asset
     * Required: true
     * Codename: image
     * Id: 8c501358-d0f7-5959-95bd-2991f1215e33
     */
    readonly image: Elements.AssetsElement;
    /**
     * Body Copy
     *
     * Type: rich_text
     * Required: true
     * Codename: body_copy
     * Id: 0747fb13-7383-59fe-bf64-2bab6d384279
     */
    readonly body_copy: Elements.RichTextElement<CoreContentType>;
    /**
     * Article Type
     *
     * Type: taxonomy
     * Required: false
     * Codename: article_type
     * Id: 2f84cb44-a29b-4f09-88f5-847d0f0b82a2
     */
    readonly article_type: Elements.TaxonomyElement<ArticleType, "article_type">;
    /**
     * General Healthcare Topics
     *
     * Type: taxonomy
     * Required: false
     * Codename: topics
     * Id: 945fa79f-fc67-480b-8e20-b777cce76ab5
     */
    readonly topics: Elements.TaxonomyElement<GeneralHealthcareTopics, "topics">;
  },
  "article"
>;

/**
 * Type representing all available element codenames for Article
 */
export type ArticleElementCodenames =
  | "title"
  | "publish_date"
  | "introduction"
  | "author"
  | "image"
  | "body_copy"
  | "article_type"
  | "topics";

/**
 * Type guard for Article
 *
 * Id: d622fc28-5202-511a-9dbf-a3ee363b6c7c
 * Codename: article
 */
export function isArticle(item: CoreContentType | undefined | null): item is Article {
  return item?.system?.type === "article";
}
