
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Karma Health Demo
* Environment: Production
* Id: d89e24b9-c2c4-0153-3e3b-8d8abd406750
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Blog
 *
 * Id: 336302c0-0634-4974-b33b-8c7b0469e837
 * Codename: blog
 */
export type Blog = CoreContentType<
  BlogElementCodenames,
  {
    /**
     * Title
     *
     * Type: text
     * Required: true
     * Codename: title
     * Id: 72869e6e-2822-4e81-944a-d90b3148ce4a
     */
    readonly title: Elements.TextElement;
    /**
     * Image
     *
     * Type: asset
     * Required: true
     * Codename: image
     * Id: 1361b589-f40e-4c4a-b219-62a0f3f5a8c0
     */
    readonly image: Elements.AssetsElement;
    /**
     * Body
     *
     * Type: rich_text
     * Required: true
     * Codename: body
     * Id: e74bc043-0613-4554-8fb5-4d03a42c61a5
     */
    readonly body: Elements.RichTextElement<CoreContentType>;
  },
  "blog"
>;

/**
 * Type representing all available element codenames for Blog
 */
export type BlogElementCodenames = "title" | "image" | "body";

/**
 * Type guard for Blog
 *
 * Id: 336302c0-0634-4974-b33b-8c7b0469e837
 * Codename: blog
 */
export function isBlog(item: CoreContentType | undefined | null): item is Blog {
  return item?.system?.type === "blog";
}
