
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Karma Health Demo
* Environment: Production
* Id: d89e24b9-c2c4-0153-3e3b-8d8abd406750
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Page } from "./index.ts";

/**
 * Call to action
 *
 * Id: a9196b8d-6320-4feb-aa25-14637761dcc6
 * Codename: call_to_action
 */
export type CallToAction = CoreContentType<
  CallToActionElementCodenames,
  {
    /**
     * Headline
     *
     * Type: text
     * Required: true
     * Codename: headline
     * Id: c3cc46c3-d5d3-4241-a83c-b4bb903f9a88
     */
    readonly headline: Elements.TextElement;
    /**
     * Subheadline
     *
     * Type: text
     * Required: true
     * Codename: subheadline
     * Id: eee46d3e-4f6e-440a-8003-2503d43d5a15
     */
    readonly subheadline: Elements.TextElement;
    /**
     * Image
     *
     * Type: asset
     * Required: true
     * Codename: image
     * Id: 8f312d9d-d8a2-484a-96c0-39391bf090db
     */
    readonly image: Elements.AssetsElement;
    /**
     * Image position
     *
     * Type: multiple_choice
     * Required: true
     * Codename: image_position
     * Id: ad7b515d-6fb0-46bd-9cd6-ca5dc1211ee2
     */
    readonly image_position: Elements.MultipleChoiceElement<"left" | "right" | "center">;
    /**
     * Button Label
     *
     * Type: text
     * Required: true
     * Codename: button_label
     * Id: ca581835-4337-4add-bdd3-aa466c685514
     */
    readonly button_label: Elements.TextElement;
    /**
     * Button Link
     *
     * Type: modular_content
     * Required: true
     * Codename: button_link
     * Id: 1872121b-6166-451e-8c26-9c78f2cfba47
     */
    readonly button_link: Elements.LinkedItemsElement<Page>;
  },
  "call_to_action"
>;

/**
 * Type representing all available element codenames for Call to action
 */
export type CallToActionElementCodenames =
  | "headline"
  | "subheadline"
  | "image"
  | "image_position"
  | "button_label"
  | "button_link";

/**
 * Type guard for Call to action
 *
 * Id: a9196b8d-6320-4feb-aa25-14637761dcc6
 * Codename: call_to_action
 */
export function isCallToAction(item: CoreContentType | undefined | null): item is CallToAction {
  return item?.system?.type === "call_to_action";
}
