
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Karma Health Demo
* Environment: Production
* Id: d89e24b9-c2c4-0153-3e3b-8d8abd406750
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Disclaimer
 *
 * Id: 01c917db-9ea5-4452-9b23-57a37f56a2c2
 * Codename: disclaimer
 */
export type Disclaimer = CoreContentType<
  DisclaimerElementCodenames,
  {
    /**
     * Content
     *
     * Type: rich_text
     * Required: true
     * Codename: content
     * Id: d8a15abf-e1c6-4949-a11a-24a4572af5c6
     */
    readonly content: Elements.RichTextElement<CoreContentType>;
    /**
     * Type
     *
     * Type: multiple_choice
     * Required: true
     * Codename: type
     * Id: d142d0ee-2163-44a0-bcfd-f4146488c858
     */
    readonly type: Elements.MultipleChoiceElement<"legal" | "informational" | "promotional" | "warning">;
  },
  "disclaimer"
>;

/**
 * Type representing all available element codenames for Disclaimer
 */
export type DisclaimerElementCodenames = "content" | "type";

/**
 * Type guard for Disclaimer
 *
 * Id: 01c917db-9ea5-4452-9b23-57a37f56a2c2
 * Codename: disclaimer
 */
export function isDisclaimer(item: CoreContentType | undefined | null): item is Disclaimer {
  return item?.system?.type === "disclaimer";
}
