
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Karma Health Demo
* Environment: Production
* Id: d89e24b9-c2c4-0153-3e3b-8d8abd406750
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Disclaimer
 *
 * Id: 01c917db-9ea5-4452-9b23-57a37f56a2c2
 * Codename: disclaimer
 */
export type Disclaimer = CoreContentType<
  DisclaimerElementCodenames,
  {
    /**
     * Headline
     *
     * Type: text
     * Required: true
     * Codename: headline
     * Id: 58fa6567-06ef-4add-a59a-a189d89b1d27
     */
    readonly headline: Elements.TextElement;
    /**
     * Subheadline
     *
     * Type: text
     * Required: true
     * Codename: subheadline
     * Id: b85982af-b575-4650-b8e7-8a34e1b0e99c
     */
    readonly subheadline: Elements.TextElement;
    /**
     * Type
     *
     * Type: multiple_choice
     * Required: true
     * Codename: type
     * Id: d142d0ee-2163-44a0-bcfd-f4146488c858
     */
    readonly type: Elements.MultipleChoiceElement<"informational" | "promotional">;
  },
  "disclaimer"
>;

/**
 * Type representing all available element codenames for Disclaimer
 */
export type DisclaimerElementCodenames = "headline" | "subheadline" | "type";

/**
 * Type guard for Disclaimer
 *
 * Id: 01c917db-9ea5-4452-9b23-57a37f56a2c2
 * Codename: disclaimer
 */
export function isDisclaimer(item: CoreContentType | undefined | null): item is Disclaimer {
  return item?.system?.type === "disclaimer";
}
