
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Karma Health Demo
* Environment: Production
* Id: d89e24b9-c2c4-0153-3e3b-8d8abd406750
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Metadata } from "../content-type-snippets/index.ts";
import type { Video, Disclaimer } from "./index.ts";

/**
 * Page
 *
 * Id: 4bdd2f8f-3acc-4744-b005-8f629948ec13
 * Codename: page
 */
export type Page = CoreContentType<
  PageElementCodenames,
  {
    /**
     * Headline
     *
     * Type: text
     * Required: false
     * Codename: headline
     * Id: 05721c93-8dcb-4daa-81b6-df690efaef61
     */
    readonly headline: Elements.TextElement;
    /**
     * Subheadline
     *
     * Type: text
     * Required: false
     * Codename: subheadline
     * Id: 719d23e7-d174-498f-b0aa-46640791b5fb
     */
    readonly subheadline: Elements.TextElement;
    /**
     * Hero Image
     *
     * Type: asset
     * Required: false
     * Codename: hero_image
     * Id: 35be9ac2-8024-410e-ab79-78709a9695f1
     */
    readonly hero_image: Elements.AssetsElement;
    /**
     * Body
     *
     * Type: rich_text
     * Required: false
     * Codename: body
     * Id: c5ac868e-97fe-419a-a256-635af1fb70aa
     */
    readonly body: Elements.RichTextElement<Video | Disclaimer>;
    /**
     * URL
     *
     * Type: url_slug
     * Required: false
     * Codename: url
     * Id: 98b67c77-04d9-47fb-9278-f38e793bb824
     */
    readonly url: Elements.UrlSlugElement;
    /**
     * Subpages
     *
     * Type: subpages
     * Required: false
     * Codename: subpages
     * Id: 17024df9-8457-45ed-ba2d-a2235a72dd06
     */
    readonly subpages: Elements.LinkedItemsElement<CoreContentType>;
  } & Metadata,
  "page"
>;

/**
 * Type representing all available element codenames for Page
 */
export type PageElementCodenames =
  | "headline"
  | "subheadline"
  | "hero_image"
  | "body"
  | "metadata__title"
  | "metadata__keywords"
  | "metadata__description"
  | "url"
  | "subpages";

/**
 * Type guard for Page
 *
 * Id: 4bdd2f8f-3acc-4744-b005-8f629948ec13
 * Codename: page
 */
export function isPage(item: CoreContentType | undefined | null): item is Page {
  return item?.system?.type === "page";
}
