
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-19'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Production
* Id: 133f5ef8-66b1-0074-7d42-55371447aac4
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Solution
 *
 * Id: f3df0cce-53f0-4ab1-875c-dd5c5d57a0ba
 * Codename: solution
 */
export type Solution = CoreContentType<
  SolutionElementCodenames,
  {
    /**
     * Headline
     *
     * Type: text
     * Required: true
     * Codename: headline
     * Id: 677e82da-9f88-49ca-9c73-2689709cbbdf
     */
    readonly headline: Elements.TextElement;
    /**
     * Introduction
     *
     * Type: text
     * Required: true
     * Codename: introduction
     * Id: c588ca2a-5cac-47b3-897d-96995c17e1f8
     */
    readonly introduction: Elements.TextElement;
    /**
     * Image
     *
     * Type: asset
     * Required: true
     * Codename: image
     * Id: 819f6844-4230-4ae1-ade7-ddb6e62ca7bd
     */
    readonly image: Elements.AssetsElement;
  },
  "solution"
>;

/**
 * Type representing all available element codenames for Solution
 */
export type SolutionElementCodenames = "headline" | "introduction" | "image";

/**
 * Type guard for Solution
 *
 * Id: f3df0cce-53f0-4ab1-875c-dd5c5d57a0ba
 * Codename: solution
 */
export function isSolution(item: CoreContentType | undefined | null): item is Solution {
  return item?.system?.type === "solution";
}
