
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Karma Health Demo
* Environment: Production
* Id: d89e24b9-c2c4-0153-3e3b-8d8abd406750
* 
* -------------------------------------------------------------------------------
**/

import type { Elements, Snippet } from "@kontent-ai/delivery-sdk";

/**
 * Metadata
 *
 * Id: 97c9abc7-223b-46a6-bf1d-061ca1db0d76
 * Codename: metadata
 */
export type Metadata = Snippet<
  MetadataElementCodenames,
  {
    /**
     * Title
     *
     * Type: text
     * Required: false
     * Codename: metadata__title
     * Id: 6acb8e2f-3e36-4a9e-9da4-85691ea88ba8
     */
    readonly metadata__title: Elements.TextElement;
    /**
     * Keywords
     *
     * Type: text
     * Required: false
     * Codename: metadata__keywords
     * Id: a84fd8ec-16f2-4ebe-9e77-59cd1fed1d49
     */
    readonly metadata__keywords: Elements.TextElement;
    /**
     * Description
     *
     * Type: text
     * Required: false
     * Codename: metadata__description
     * Id: 2223c595-ac0e-4ea9-b767-67b47d19d6bc
     */
    readonly metadata__description: Elements.TextElement;
  }
>;

/**
 * Type representing all available element codenames for Metadata
 */
export type MetadataElementCodenames = "metadata__title" | "metadata__keywords" | "metadata__description";
